### ISSUE TITLE
AddressMetaData Uniqueness issue with Nova Flexible Content

### ISSUE THREAD

**Issue by chirag-nandaniya** [YieldStudio/nova-google-autocomplete#5]
Using this extension with Flexible Content(https://github.com/whitecube/nova-flexible-content). But latest meta data replace in all destinations. Anything you can do for uniqueness in DOM on particular page.

Flexible::make('Destinations', 'destinations')
->addLayout('Destinations', 'destinations', [
    GoogleAutocomplete::make('Destination')
    ->withValues(['latitude', 'longitude', 'street_number', 'route', 'locality', 'administrative_area_level_1.long_name', 'country', 'postal_code']),

    // And you can store the values by autocomplete like this
    AddressMetadata::make('Latitude')->fromValue('latitude')->disabled(),
    AddressMetadata::make('Longitude')->fromValue('longitude')->disabled(),
    AddressMetadata::make('City')->fromValue('locality')->disabled(),
    AddressMetadata::make('State/Province')->fromValue('administrative_area_level_1')->disabled(),
    AddressMetadata::make('Country')->fromValue('country')->disabled(),
])
->collapsed(true)
->button('Add Destination')
->stacked(),

**Comment by JamesHemery** [comment]
Hi @chirag-nandaniyan,

I'm open to review a PR :)
